# .github/workflows/test.yml

name: Test API Loader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Remove Windows-only packages (e.g. pywin32)
        run: |
          sed -i '/pywin32/d' requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi==0.95.2 starlette==0.27.0
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run unit tests
        env:
          DISABLE_MODEL_LOADING: "1"   # ✅ Ajout ici
        run: |
          pytest tests/
